= Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"index", type text}, {"clusters", Int64.Type}, {"Topic_1", type number}, {"Topic_2", type number}, {"Topic_3", type number}, {"Topic_4",  type number}, {"Topic_5", type number}, {"Topic_6", type number}, {"Topic_7",  type number}, {"Topic_8", type number}, {"Topic_9", type number}, {"Topic_10", type number}, {"Topic_11", type number}, {"Topic_12", type number}, {"Topic_13", type number}, {"Topic_14",type number}, {"Topic_15",type number}, {"Topic_16", type number}, {"Topic_17", type number}, {"Topic_18", type number}, {"Topic_19", type number}, {"Topic_20", Int64.Type}, {"Topic_21", type number}, {"Topic_22", type number}, {"Topic_23", type number}, {"Topic_24", type number}, {"Topic_25", type number}, {"Topic_26", type number}, {"Topic_27", type number}, {"Topic_28", type number}, {"Topic_29", type number}, {"Topic_30", type number}, {"Topic_31", type number}, {"Topic_32", type number}, {"Topic_33", type number}, {"Topic_34", type number}, {"Topic_35", type number}, {"Topic_36", type number}, {"Topic_37", type number}, {"Topic_38", type number}, {"Topic_39", type number}, {"Topic_40", type number}, {"Topic_41", type number}, {"Topic_42", type number}, {"Topic_43", type number}, {"Topic_44", type number}, {"Topic_45", type number}, {"Topic_46", type number},{"channel", type text}, {"day", type date}},"en-US")opic_32", type number}, {"Topic_33", type number}, {"Topic_34", type number}, {"Topic_35", type number}, {"Topic_36", type number}, {"Topic_37", type number}, {"Topic_38", type number}, {"Topic_39", type number}, {"Topic_40", type number}, {"Topic_41", type number}, {"Topic_42", type number}, {"Topic_43", type number}, {"Topic_44", type number}, {"Topic_45", type number}, {"days_completed", type date}},"en-US")